/**
 * API conformance — every path the RN client calls must exist on the server.
 *
 * This is the test that would have caught the bug class that has shipped at
 * least four times: `/match/matches` vs `/match/mutual`, `/chat/:id` vs
 * `/chat/messages/:id`, `/auth/refresh-token` vs `/auth/refresh`,
 * `/verification/me` vs `/verification/status`.
 *
 * Why it reads SOURCE instead of importing the modules: importing `api/*.ts`
 * pulls in the axios client, the auth store and MMKV, and the only way to make
 * that work under jest is to mock axios — at which point the assertion is
 * against the mock. When the path is wrong, the mock is wrong in exactly the
 * same way, so a mocked test agrees with the bug. Parsing the call sites keeps
 * the client's real strings on one side and the server's real router on the
 * other, with nothing in between to agree with either.
 *
 * The manifest is generated by backend/tests/unit/routeManifest.test.js from the
 * live Express router. Regenerate it with `npm run test --workspace=backend`.
 */

import { readFileSync, readdirSync } from 'fs';
import { join } from 'path';

type Manifest = { prefix: string; alias: string; routes: string[] };

const API_DIR = __dirname;
const manifest: Manifest = JSON.parse(
  readFileSync(join(__dirname, '..', '..', '..', 'shared', 'src', 'constants', 'api-manifest.json'), 'utf8')
);

/** `GET /api/v1/profile/:id` -> `GET /profile/:id` (client paths are prefix-relative). */
const serverPaths = new Set(
  manifest.routes.map((r) => {
    const [method, full] = r.split(' ');
    return `${method} ${full.slice(manifest.prefix.length)}`;
  })
);

/**
 * Normalise a client path template to the server's param shape:
 *   `/profile/${userId}/compatibility` -> `/profile/:p/compatibility`
 * Query strings are stripped — Express routes do not include them.
 */
const normalise = (p: string) =>
  p
    .split('?')[0]
    .replace(/\$\{[^}]+\}/g, ':p')
    .replace(/\/+$/, '') || '/';

const normaliseServer = (p: string) => p.replace(/:[A-Za-z0-9_]+/g, ':p').replace(/\/+$/, '') || '/';

const serverNormalised = new Set([...serverPaths].map((r) => {
  const [method, p] = r.split(' ');
  return `${method} ${normaliseServer(p)}`;
}));

/** Every `apiClient.<verb>(...)` / `client.<verb>(...)` call site in api/*.ts. */
const CALL_RE = /\b(?:apiClient|client)\s*\.\s*(get|post|put|patch|delete)\s*(?:<[^(]*>)?\s*\(\s*(['"`])([^'"`]+)\2/g;

interface CallSite {
  file: string;
  method: string;
  path: string;
}

/**
 * Modules excluded from the "must exist on the server" assertion.
 *
 * `bureau.ts` calls /bureau/clients, /bureau/earnings and /bureau/proposals.
 * There is no bureauRoutes.js on the backend at all — the entire RN bureau
 * feature talks to endpoints that have never existed. It is known dead code
 * awaiting the bureau-channel memo decision (docs/BUREAU_CHANNEL_MEMO_2026-08-09.md),
 * and deleting a feature is an owner call, not a test's. It is listed here
 * explicitly so it stays visible rather than quietly passing.
 */
const KNOWN_DEAD_MODULES = new Set(['bureau.ts']);

const collectCallSites = (): CallSite[] => {
  const sites: CallSite[] = [];
  for (const file of readdirSync(API_DIR)) {
    if (!file.endsWith('.ts') || file.endsWith('.test.ts')) continue;
    if (KNOWN_DEAD_MODULES.has(file)) continue;
    const src = readFileSync(join(API_DIR, file), 'utf8');
    for (const m of src.matchAll(CALL_RE)) {
      sites.push({ file, method: m[1].toUpperCase(), path: m[3] });
    }
  }
  return sites;
};

describe('api conformance', () => {
  const sites = collectCallSites();

  it('actually found the client call sites (guards against a silent regex miss)', () => {
    // Without this, a change to how requests are issued would make every other
    // assertion below vacuously pass over an empty list.
    expect(sites.length).toBeGreaterThan(40);
    expect(new Set(sites.map((s) => s.file)).size).toBeGreaterThan(8);
  });

  it('loaded a server manifest', () => {
    expect(manifest.routes.length).toBeGreaterThan(50);
    expect(manifest.prefix).toBe('/api/v1');
  });

  it('every path the client calls exists on the server', () => {
    const missing = sites
      .filter((s) => {
        const key = `${s.method} ${normalise(s.path)}`;
        return !serverNormalised.has(key);
      })
      // Report each unique offender once, with its file, so the failure names
      // the fix instead of just the count.
      .map((s) => `${s.file}: ${s.method} ${s.path}`);

    expect([...new Set(missing)]).toEqual([]);
  });

  it('pins the known-dead modules so they cannot be forgotten', () => {
    // If someone builds the backend for these, or deletes the RN feature, this
    // fails and forces the exclusion list to be updated rather than left to rot.
    const bureau = readFileSync(join(API_DIR, 'bureau.ts'), 'utf8');
    expect(bureau).toMatch(/\/bureau\//);
    expect([...KNOWN_DEAD_MODULES]).toEqual(['bureau.ts']);
  });

  it('no client path hardcodes the api prefix (baseURL already carries it)', () => {
    // EXPO_PUBLIC_API_URL ends in /api/v1, so a path that repeats it produces
    // /api/v1/api/v1/... — a 404 that only shows up against a real server.
    const doubled = sites
      .filter((s) => s.path.startsWith('/api/'))
      .map((s) => `${s.file}: ${s.path}`);
    expect(doubled).toEqual([]);
  });
});
